#pragma once

// The Rust FFI boundary. `sdk-core.h` is generated by cbindgen from
// `core/ffi` at build time (see CMakeLists.txt), so the C++ side never
// mirrors the ABI by hand and cannot drift from it.
//
// Ownership conventions (see core/ffi/src/lib.rs):
//   * `BorrowedStr` is never freed by C++. Inputs and callback payloads are
//     valid for the duration of the call; strings inside structured results
//     until that result's `*__free`.
//   * `OwnedStr`, `FfiOwnedVariation`, `FfiVariations`, `FfiDataFile` and
//     `FfiError` written to an `out`/`error` parameter must be released with
//     the matching `*__free` function; detail/result.hpp wraps them in RAII
//     owners that copy the borrowed strings into the public types before
//     releasing.

// The generated header includes these itself; pulling them in at global scope
// first makes the includes below (inside the namespace) guarded no-ops.
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// cbindgen models Rust data enums as a tag plus an anonymous union of
// anonymous structs, which is a C extension every supported compiler accepts.
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgnu-anonymous-struct"
#pragma clang diagnostic ignored "-Wnested-anon-types"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
#endif

// cbindgen's `cpp_compat` already emits `extern "C"`; repeating it keeps the
// declarations C-linkage (and thus linkable) with headers generated without it.
namespace kameleoon::detail::ffi
{
    extern "C"
    {
#include "sdk-core.h"
    }
} // namespace kameleoon::detail::ffi

#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
